### ISSUE TITLE
Crash and glitch on GWT export

### ISSUE THREAD

**Issue by Kromzem** [intrigus/gdx-freetype-gwt#2]
I got a weird bug and I'm not sure if this problem is on my side or in this library. 
Everytime I set the FreeTypeFontParameter "shadowOffsetX" and "shadowOffsetY" I get following exception: 
com.google.gwt.core.client.JavaScriptException: (TypeError) : P.cX is not a function

I don't know how to fix that because everything i tried is not working ... I can use every parameter except these two.

EDIT:
I found the source of the failure. File: FreeTypeFontGenerator   Line: 538
He fails to cast the pixmap correctly

UPDATE:
i just changed the casting an get weird looking effects:
![unbenannt](https://cloud.githubusercontent.com/assets/6073096/25376201/a23e0000-29a3-11e7-9bac-6f95ed3ae862.png)

**Comment by intrigus** [comment]
Could you please share a sample project?
Also, which version of libgdx are you using?

**Comment by Kromzem** [comment]
I will share a sample as soon as I can ;) I'm using the current version 1.9.6. And anyways, great work :)

**Comment by intrigus** [comment]
@Kromzem Did you resolve the issue or can you now share a sample?

**Comment by intrigus** [comment]
Closing since there hasn't been an answer for quite some time.
