### ISSUE TITLE
pls fix bug  Mac OS iphone  can not be used

### ISSUE THREAD

**Issue by chongbo2013** [intrigus/gdx-freetype-gwt#6]
Because I don't know how to grab the mac os or Apple phone logs, but once I comment out the font-related code, I can run normally.
Online project urgent, ask for help

**Comment by chongbo2013** [comment]
mac com.google.gwt.core.client.JavaScriptException(InvalidStateError) The object is in an ivalid state

**Comment by intrigus** [comment]
Closing as duplicate of https://github.com/intrigus/gdx-freetype-gwt/issues/7
since the root cause is probably the same.
