### ISSUE TITLE
freetype.js loads infinity

### ISSUE THREAD

**Issue by SimonIT** [intrigus/gdx-freetype-gwt#8]
I included this lib like your instructions in the readme.
You can see in the screenshot, that `freetype.js` loads infinity.
![CollapseTheGame - Google Chrome 06 12 2019 22_14_12](https://user-images.githubusercontent.com/11720038/70356897-cbf08800-1875-11ea-9e55-6231b5f5d96f.png)

I'm using libgdx version 1.9.11-SNAPSHOT. I load my ttf via the asset manager like [here ](https://github.com/libgdx/libgdx/wiki/Managing-your-assets#loading-a-ttf-using-the-assethandler) described in the wiki. If you want, I can invite you to the project

**Comment by intrigus** [comment]
Please invite me to the project :)

**Comment by SimonIT** [comment]
Done

**Comment by intrigus** [comment]
Hmm, I see nothing obvious wrong in your project setup.
Looking at my source I also found nothing that is obviously wrong.

Can you get a "stack traces" of the resource loading part?
I.e. which code is triggering the loading?

My guess would be that some new (security) feature maybe doesn't allow injecting Javascript in certain cases?
The code I'm using for injection is also not my code, but GWT code:
https://github.com/intrigus/gdx-freetype-gwt/blob/master/src/com/badlogic/gdx/graphics/g2d/freetype/gwt/FreetypeInjector.java#L40

I'm not sure when I'll have time to look at the problem myself. Maybe after Christmas.

**Comment by SimonIT** [comment]
The injection seem to work:
![image](https://user-images.githubusercontent.com/11720038/70389202-7bd00d80-19bc-11ea-9b91-32ed0cfd6e56.png)

I don't know how to print a stacktrace if there is no exception.
It seems that `onModuleLoad` in my own HTML Launcher gets everytime called.
I fixed it by replacing `FreetypeInjector.inject(HtmlLauncher.super::onModuleLoad);` with `FreetypeInjector.inject(super::onModuleLoad);`.

**Comment by intrigus** [comment]
Could you please try whether the official method works?
I.e. using no Lambdas?

Because I'm not sure whether there should be any difference between `HtmlLauncher.super::onModuleLoad` and `super::onModuleLoad`.
I'd assumed that they would work the same way.

````java
@Override
public void onModuleLoad () {
	FreetypeInjector.inject(new OnCompletion() {
		public void run () {
			// Replace HtmlLauncher with the class name
			// If your class is called FooBar.java than the line should be FooBar.super.onModuleLoad();
			HtmlLauncher.super.onModuleLoad();
		}
	});
}
````

**Comment by SimonIT** [comment]
Your code without lambda works fine. I thought the two statements are the same, too. It was IntelliJ which made the lambda expression.

**Comment by intrigus** [comment]
@SimonIT I guess this can be closed, right?

**Comment by SimonIT** [comment]
Yes, you reopened it :)

**Comment by intrigus** [comment]
Whoops ^^
